theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
cursorline = true
color-modes = true
true-color = true
rulers = [88]  # Black's default line length
idle-timeout = 50

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.lsp]
display-messages = true
auto-signature-help = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics", "workspace-diagnostics"]
right = ["version-control", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
C-q = ":q"
C-f = "file_picker"
"tab" = "goto_next_buffer"
"S-tab" = "goto_previous_buffer"
"space" = { f = "file_picker", w = ":w", q = ":q", r = ":config-reload", i = ":pipe python -m isort -" }

[keys.insert]
"C-space" = "completion"
