[[language]]
name = "python"
scope = "source.python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "pyx", "pxd"]
shebangs = ["python", "python3"]
roots = ["pyproject.toml", "setup.py", "Poetry.lock", "requirements.txt"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

language-servers = [
  { name = "pyright", except-features = [
    "format",
  ] },
  { name = "ruff", except-features = [
    "format",
  ] },
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
python.analysis.typeCheckingMode = "basic"
python.analysis.diagnosticMode = "workspace"
python.analysis.autoSearchPaths = true
python.analysis.useLibraryCodeForTypes = true
python.analysis.diagnosticSeverityOverrides = { reportGeneralTypeIssues = "warning" }

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lineLength = 88 # same as black

# For TOML configuration files
[[language]]
name = "toml"
scope = "source.toml"
file-types = ["toml"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

# For requirements files
[[language]]
name = "requirements"
scope = "source.requirements"
file-types = ["requirements.txt", "requirements-dev.txt"]
